checks:
    javascript: true
filter:
    excluded_paths:
        - test/*
build:
    dependencies:
        before:
            - npm install istanbul
    environment:
             node: '4.2.2'
    tests:
        override:
            - npm test
            - eslint-run --config .eslintrc index.js
            -
                command: 'npm run coverage-clover'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
